name: release(beta)

on:
  push:
    tags:
      - "*-beta.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm i -g pnpm@10.10.0
          pnpm i --frozen-lockfile

      - name: Test
        run: pnpm test:ci

      - name: Build
        run: pnpm build

      - name: Publish
        run: |
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
