name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Deps
        run: |
          npm i -g pnpm@10.10.0
          pnpm i --frozen-lockfile
      - name: Test
        run: pnpm test:ci
